# -*- coding: utf-8 -*-
"""AD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q94kxG0lbUy99OVwUJCgZ6yzv9ZZqLue
"""

!pip install transformers torch

!pip install gradio

from transformers import BartForConditionalGeneration, BartTokenizer
import gradio as gr

# Load the BART model and tokenizer
model_name = "facebook/bart-large-cnn"
model = BartForConditionalGeneration.from_pretrained(model_name)
tokenizer = BartTokenizer.from_pretrained(model_name)

# Summarization function
def summarize_text(input_text):
    inputs = tokenizer(input_text, return_tensors="pt", max_length=1024, truncation=True)
    summary_ids = model.generate(inputs['input_ids'], max_length=200, min_length=50, length_penalty=2.0, num_beams=4, early_stopping=True)
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    return summary

# Create Gradio interface
interface = gr.Interface(
    fn=summarize_text,
    inputs=gr.Textbox(lines=10, placeholder="Enter your text here..."),
    outputs=gr.Textbox(label="Summary"),
    title="Text Summarizer",
    description="Enter long text to generate a concise summary using BART."
)

# Launch the interface
interface.launch()



!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from transformers import BartForConditionalGeneration, BartTokenizer
# 
# # Load the BART model and tokenizer
# model_name = "facebook/bart-large-cnn"
# model = BartForConditionalGeneration.from_pretrained(model_name)
# tokenizer = BartTokenizer.from_pretrained(model_name)
# 
# def summarize_text(input_text):
#     inputs = tokenizer(input_text, return_tensors="pt", max_length=1024, truncation=True)
#     summary_ids = model.generate(inputs['input_ids'], max_length=200, min_length=50, length_penalty=2.0, num_beams=4, early_stopping=True)
#     summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
#     return summary
# 
# # Streamlit UI
# st.title("Text Summarizer")
# input_text = st.text_area("Enter your text:", height=300)
# if st.button("Summarize"):
#     if input_text:
#         summary = summarize_text(input_text)
#         st.subheader("Summary:")
#         st.write(summary)
#     else:
#         st.warning("Please enter some text to summarize.")
#

!streamlit run app.py & npx localtunnel --port 8501